<?php
/**
 * CharZam_Controller
 *
 * NOTICE OF LICENSE
 *
 * Copyright (C) 2018  Improove
 *
 * CharZam_Controller is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CharZam_Controller is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CharZam_Controller.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    CharZam
 * @package     CharZam_Controller
 * @copyright   Copyright (C) 2018 Improove (http://www.improove.se/)
 * @license     http://www.gnu.org/licenses/agpl-3.0.html
 * @author      Peter Lembke <peter.lembke@improove.se>
 */
/** @var $block \CharZam\Controller\Block\MyPage */
?>
<div class="block block-my-page">
    <div class="block-title">
        <strong id="block-my-page-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('My page header')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-my-page-heading">
        <p><?= $block->escapeHtml(__('Test page to show the page result')) ?></p>
        <?php $row = 'My Page!!'; ?>
        <p><?php echo $row . ' become: ' . $block->convertString($row); ?></p>
        <p><?php echo 'Example string: ' . $block->getData('example_string'); ?></p>
        <p><?php echo 'Example boolean: ' . $block->getData('example_boolean'); ?></p>
    </div>
</div>
