<?php
/**
 * CharZam_Layout
 *
 * NOTICE OF LICENSE
 *
 * Copyright (C) 2018  Improove
 *
 * CharZam_Layout is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CharZam_Layout is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with CharZam_Layout.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    CharZam
 * @package     CharZam_Layout
 * @copyright   Copyright (C) 2018 Improove (http://www.improove.se/)
 * @license     http://www.gnu.org/licenses/agpl-3.0.html
 * @author      Peter Lembke <peter.lembke@improove.se>
 */
/** @var $block \CharZam\Layout\Block\MyPage */
?>
<div class="block block-another-page">
    <div class="block-title">
        <strong id="block-another-page-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Another page header')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-another-page-heading">
        <p><?= $block->escapeHtml(__('Another test page to show the page result')) ?></p>
        <?php $row = 'foobar'; ?>
        <p><?php echo $row . ' become: ' . $block->convertString($row); ?></p>
        <p><?php $data = $block->getData(); ?></p>
        <p><?php var_dump($data); ?></p>
    </div>
</div>
